name: chatwoot_flutter
description: An unofficial flutter client sdk for chatwoot. Integrate Chatwoot into your flutter app.
version: 2.0.0-dev.1
repository: https://github.com/MarkIvanDev/chatwoot_flutter.git
issue_tracker: https://github.com/MarkIvanDev/chatwoot_flutter/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  web_socket_channel: ^3.0.3
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  riverpod: ^2.5.1
  synchronized: ^3.1.0+1
  intl: ^0.20.2
  flutter_chat_types: ^3.6.2
  # stream_channel: ^2.1.2
  # async: ^2.11.0
  # flutter_inappwebview: ^6.0.0
  flutter_secure_storage: ^10.0.0-beta.4
  url_launcher: ^6.2.6
  # path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^5.4.4
  # json_serializable: ^6.9.0
  # hive_generator: ^2.0.1
  # build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  # path_provider_platform_interface: ^2.1.2
  # plugin_platform_interface: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
